### ISSUE TITLE
Crashing in Safari 

### ISSUE THREAD

**Issue by cencio1952** [fastaddons/GroupSpeedDial#108]
**Describe the bug**
Everytime I add a new dial or add or change a thumbnail, I'm not able to open again the related Group.
The only way to unlock is to open another browser, make a backup and restore in Safari
**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: MacOS Monterey 12.1
 - Browser and version: Safari 15.2
 - GroupSpeedDial version: 18.0

**Additional info**
Add any other info about the problem here.

**Comment by fastaddons** [comment]
Hello,
Could you give me more info? When you say you can't open the group again, what exactly happens? Is there some error? Or Safari will freeze?
Also, when did this started?
Will thumbnail reload also cause this?

**Comment by cencio1952** [comment]
Hello Juraj

I’ve recorded the screen, so you can see what happens.
I don’t remember when it started, but it has been a long time, for sure months

Ciao
Vincenzo

**Comment by fastaddons** [comment]
Hello again,
This is a github notification email, so you can't send it attachments (if you did).
Also this conversation is public on github:
https://github.com/fastaddons/GroupSpeedDial/issues/108

So private data send only directly to my email (I can't write because it will be stripped out). But you can find it in the Options page / About tab (in my addon).
