### ISSUE TITLE
All groups and speed dials disappeared 

### ISSUE THREAD

**Issue by ais-lingua** [fastaddons/GroupSpeedDial#112]
Opened FF 96.0.2 0 All extensions were missing. 
Re-loaded FF. Extenstions re=appeared but were initialized

Got the welcome/intro screen for Group Dials.
 All groups and speed dials are missing. History had one  auto backup of the home page; none of my other 2 groups.

Where are the local dials stored?

**Comment by fastaddons** [comment]
Hello,
Well, this is bad.
Addons doesn't have access to the drive anymore. All addons data are "somehow" stored by the browser. For example Firefox uses some kind of SQLite database - it may be able to recover it, but it's for sure not gonna be easy and I really don't know how.

The automatic backup you see in the History is a special backup stored in special store that can survive even uninstalling, but it has a limited size so it's updated only every few days, that's why it's so old (and the other local backups were clearly deleted with other addons data).

So anyway, if you don't have an exported backup file or a Cloud account, I'm not sure you will be able to restore it. I'm really sorry for the bad news :(

Can you tell me what exactly happened, how did your Firefox lost all extensions?
