### ISSUE TITLE
Tile Images Gone Again

### ISSUE THREAD

**Issue by ITGeekMonkeys** [fastaddons/GroupSpeedDial#122]
I've been using this addon for a couple of years now and I LOVE it except for the following problem.
This issue has occurred twice, wherein all of the images associated with the dials are somehow deleted.
Explain to me how the cloud storage of dial images can just go bye bye?
![Capture](https://user-images.githubusercontent.com/4103343/157757588-674c151e-1bc0-46d1-935b-08c0f975887e.JPG)
vanish?

**Comment by fastaddons** [comment]
Images are big, so they are stored in the special "IndexedDB" database which is (sadly) pretty fragile in browsers - in Firefox it can temporary (or fully) break, in Chrome some records gets corrupted and can't be recreated (plus some huge memory leak) and Safari is just insane.

First, try to restart your PC, that can fix the issue right away.

Also - if you enable thumbnails synchronization, they will be backed up in the cloud and will be automatically restored. See Options page / Thumbnails / "Enable automatic thumbnails synchronization with the cloud server".
(I'm not promoting much because server storage is expensive and I'm running out of space... but I do plan to upgrade into different cheaper provider).

**Comment by ArtCGecko** [comment]
I was going to pay for the Pro but the free one does not work 90% of the time.  Images are gone most of the time.  Love it when it does work but I don't want to keep restarting my computer every time I open a new tap.

**Comment by fastaddons** [comment]
Hello again,
Could you please try to visit this storage test page?
https://firefox-storage-test.glitch.me/
(the test takes about 10 seconds and you should see "Storage is working." message)

Also, could you describe the problem more? You thumbnails disappear during the day and restarting PC brings them back?
And lastly, do you use some PC cleaning tools or addons that can remove history / cookies / cache / etc...?
