### ISSUE TITLE
Changing URL of an existing dial, also changes the title

### ISSUE THREAD

**Issue by bbley1** [fastaddons/GroupSpeedDial#128]
**Steps To Reproduce**

Create a dial. For example www.google.com with a custom title.

Now edit the dial. Change its URL to something else. (for example www.google.co.uk)

**Expected behavior**

When we change a Dial's URL in edit menu, it shouldnt make changes to Dial's title

**Device info:**
 - GroupSpeedDial version: 18.3

**Comment by fastaddons** [comment]
Yeah, this is by design. Usually when URL changes, it means it points to a different page now, so the old name is most likely not matching anymore.

But I see the issue with your use-case. Maybe I could show some new button/icon when URL is updated that user can click to cancel new name update. Maybe next to Dial title field, or inside it. I'll try to add something now.

**Comment by bbley1** [comment]
Something like that would be useful in case we need to make changes to URLs. Thank you. Closing this one as well.
