### ISSUE TITLE
19.1 is using WebP thumnails which doesn't work if WebP is disabled in Firefox config using "image.webp.enabled"

### ISSUE THREAD

**Issue by paulholder** [fastaddons/GroupSpeedDial#130]
I have a number of dials set to auto-refresh every so often.  Earlier today I noted all the ones meant to refresh are now showing a broken page icon.  I looked at recently updated extensions and GroupSpeedDial was recently updated, so I presume that is the source of the issue.  This is what I'm seeing:  https://snipboard.io/nMD1wc.jpg

**Comment by fastaddons** [comment]
Yeah, that is most probably related to the update, but not the refresh problem, this is a not-working image problem, more like a database issue.

Let's investigate:
1. what browser version do you use? It must be some Firefox since I haven't released Chrome version yet.
2. try to restart Firefox, does that help?
3. right click on the browser tab and select "Open in New Container Tab" and select any of the containers - will this load images?
4. while on the broken dials page, could you press "Ctrl + Shift + K" and copy and paste any red messages you see there?

**Comment by fastaddons** [comment]
Oh, and also I've switched to WebP image format, could check this image if it loads for you:
https://upload.wikimedia.org/wikipedia/commons/a/a1/Johnrogershousemay2020.webp

**Comment by paulholder** [comment]
> switched to WebP 

Aha, that would do it.  I have disabled WebP and WebM in Firefox because I was finding it was causing me problems.  I'm unwilling to re-enable it just for your extension I'm afraid.  I guess I will have to find a work-around.  :/

**Comment by paulholder** [comment]
Just to let you know, I did toggle the advanced config "image.webp.enabled" and it started working again.  And stopped again when I toggled it back off...  so that was definitely the issue.

**Comment by fastaddons** [comment]
Interesting... I didn't know one can disable support for an image format, that's crazy.
Can you tell me what kind of problems was WebP causing for you? And isn't this breaking also some normal pages on the web? 
The WebP is getting pretty popular these days because all modern browsers supports it.

I'm gonna leave this open, there may be others with this issue.

**Comment by paulholder** [comment]
> what kind of problems was WebP causing for you?
It's sites like Reddit and Imgur, where the infrastructure (probably their CDN?) replaces JPGs with "smaller" files like WebP's.  But the image quality is less, and I don't like it.

> isn't this breaking also some normal pages on the web?
When I disabled the file format, the header sent to the site changes, which causes them to select a different (the original, most likely) image to send instead.  I also disabled AV1 based files for the same reason.  Here you can see the headers with everything enabled, and then with the two types disabled.

Accept   text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept   text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,*/*;q=0.8
Accept   text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

The headers were determined using https://manytools.org/http-html-text/http-request-headers/

The only site that noticeably "broke" was YouTube's thumbnails in *some* circumstances.  Since that disabled other annoyances of YouTube to, I was more than satisfied with the result.

Since I run with scripts disabled, and no 3rd party cookies, I am used to sites appearing to be broken.  Usually it's easy enough to work around, and if it's not, I just copy the URL to Chrome for that once site.

**Comment by fastaddons** [comment]
Those are some pretty drastic solutions :)
There may be a better way, there is an extension from a known addon developer that will simply make Firefox not send the `image/webp` (and optionally also `avif`) string in the `Accept` header, so the server will send jpeg or other backup format if it has one BUT if it doesn't have anything else, it will use WebP or AVIF and they will still work.
https://addons.mozilla.org/firefox/addon/dont-accept-webp/

**Comment by paulholder** [comment]
Thanks for the pointer to this extension.  It's a great solution/workaround... and now I can have my dials back.
