### ISSUE TITLE
White screen with top 4 buttons only

### ISSUE THREAD

**Issue by Tiffys** [fastaddons/GroupSpeedDial#141]
**Describe the bug**
As of today my speed dial consists exclusively of a pure white screen with no icons, text, buttons, thumbnails, nor anything else except the 4 buttons on the top right: < Home cloud and the menu thing.

It seems to be somewhat intermittent with the problem coming and going.

**Steps To Reproduce**
I wish I knew.

**Device info:**
 - operating system: Windows 10 Pro
 - Browser and version: 102.0.5005.63 (formerly also on 102.0.5005.62)
 - GroupSpeedDial version: 19.9

**Comment by fastaddons** [comment]
Hello,
Do you remember doing something special before this happened?
Like running CCleaner or similar tool to optimize / speed up PC?

Anyway, see this article about backup and fixing dials page:
https://github.com/fastaddons/GroupSpeedDial/wiki/Fixing-broken-dials-page

**Comment by fastaddons** [comment]
Interesting, yeah I have no idea what that was, but if you see it next time, please make a screenshot.

Browsers breaks "a lot" these days since they are updated every 4 weeks with new features, which is great, but it brings also some new and often hard to find bugs (like "race condition").

PS: that's a pretty nice PC spec. you have there! :)
