### ISSUE TITLE
New Groupspeed Dial / or new edge version

### ISSUE THREAD

**Issue by FAdamfamily** [fastaddons/GroupSpeedDial#142]
hello Jurai,
I have tried everything with edge and Groupspeed Dial, deleted and reinstalled Groupspeed Dial, uninstalled and reinstalled edge, etc. Groupspeeddial periodically loses thumbails and reports "create thumbnail".

Now i returned to Firefox and all problems are solved.

regards Friedhelm

**Comment by fastaddons** [comment]
Hello,
Thumbnails are big so they are stored in a special IndexedDB database. Sadly this database implementation is imperfect in browsers and sometimes breaks.
But if reinstalling didn't helped then I would guess something deleted it to "free space". If you are using CCleaner or other tool to optimize / clean PC, it's most probably the source of the problem. Also it's important to use up-to-date versions because old versions can delete wrong files.
