### ISSUE TITLE
My suggestions for changes and new stuff for Group Speed Dial

### ISSUE THREAD

**Issue by RemixPL1994** [fastaddons/GroupSpeedDial#146]
1. I found an option to reduce and enlarge the font in thumbnail captions, eg where I write at the bottom of Google. But I can't find an option for the text to be centered instead of to the left. Could you add this option or if I can't see it tell me where I can center the text for thumbnail captions?

In addition to the option to choose to set the logos and signatures to "centered", it would also be useful to set the font bold.

![obraz](https://user-images.githubusercontent.com/52541621/174313048-fa777c5b-f605-4b52-b2bd-04d36b546196.png)

As for the ability to center the text, it would be good if you set the text of the caption itself or the text + image / logo of the page thumbnail next to the caption as it is now.

However, I do not think that changing the font type is something very necessary, but you can think about it sometime, later to also give a selection of characters in the abbreviations at the bottom :)

2. It would be very nice if you could separately set where the shortcut names should appear at the bottom.

Ie now he can either turn them on or off "everywhere".

I wish I could set the shortcut names at the bottom wherever I have Split dial set to - Normal.

And where I have Split dial set to - Horizontal half or Horizontal thirds, I'd like to set it separately to make the shortcut names at the bottom invisible.

I present it here where it is marked where I would like it not to be seen:

![obraz](https://user-images.githubusercontent.com/52541621/174314089-bdfbd150-0819-4382-8272-40dd9fedc666.png)

3. I know that this is your addition and you may not agree to my idea, but if you could give options and settings, optionally for those willing (eg me), to change the logo itself. the button that shows up as an add-on on the browser bar?

The point is:

![obraz](https://user-images.githubusercontent.com/52541621/174315050-2d636356-69e0-4ce4-9a9c-f4400528f651.png)

To change optionally in options to such or similar:

![obraz](https://user-images.githubusercontent.com/52541621/174315079-555869fa-5e8d-4441-8d94-aa46db85c41d.png)

If you want to ask why? for what? I am explaining this already

Since I started using the Fast Dial add-on on the old firefox, and then Quick Dial, I got used to these 4 colored "squares" as logos that symbolize my tab windows. I just got used to and learned that my start page and tabs are under this symbol.

Now I want to use Group Speed Dial because it is the best technically and most customizable but I will be missing the old logo and I will be before I miss it. Adding something like I have shown or another a little alternative would be a godsend for me so that I could continue to use what I have got used to for a long time.

4. I like to use Speed Group Dial with "Hide groups and login" set:

![obraz](https://user-images.githubusercontent.com/52541621/174315913-bc5030ed-bae3-405c-a157-4774fb4048f3.png)

But I noticed that under PMM when I click on the tabs or directly on the tab, the quick selection to enter "options" does not appear.

I saw in the settings in the context menu that you can set and hide various fields to be shown or not, but I have nowhere found a choice so that after hiding groups and logging in, I could quickly open options via PPM and go to them directly.

In addition, if possible, it would be nice that the information about the connection and logging in to the cloud, user name and license type was displayed in the options in the "Information" section at the very bottom.

Now that I have "Hide groups and login" set, I actually have permanently hidden login information.

It would be good if this information was included in the "Information" tab, because after hiding the button, it is impossible to return to them, as well as to the PPM options mentioned above.

5. This question of mine is more complicated and more advanced.

If I created my account by entering my name, email and password (without using a google account etc.), can I secure the login to my cloud account in Group Speed ​​Dial somehow on 2FA or U2F?

Is it feasible in some way?

Why am I asking about such things? Because network security is important to me and I always try to have at least two-step authentication on email / SMS / one-time codes generated from the application set up.

And of course, the best way is to add your physical key, eg Yubikey, so that logins are always 100% secure.

But implementing Yubikey keys can be very hard and time consuming, but perhaps adding generated codes from a mobile app or confirmation links / codes sent to email may be done at first and will suffice - and it will always be better than no security at all.

**Comment by fastaddons** [comment]
Hello,
I'm sorry for the delay! I've been very busy these last weeks or even months.
I will have more time now since I've finished the huge Manifest V3 migration.

The detailed changelog is currently only here:
https://addons.mozilla.org/en-US/firefox/addon/groupspeeddial/versions/

I haven't read your long text above yet, I'll do it right now!

Regarding your notes above:
1. centering is done :). 
But the bold looks terrible, it may be better if I had some "Font picker", but that's planned only after I migrate Options page to "Vuetify", which is probably not happening this year.
But you can make the titles bold by using "Custom CSS styles" in the Options page / General tab.
Set it to:
```css
.dial_head {
  font-weight: bold;
}
```
Regarding text + logo style, this is now possible using the new "List view" layout. Right click group / Edit group / "List". This feature is released only in Firefox, Chrome version should be released soon.

3. **I like the idea with hiding title bar on individual dials, that sounds really cool. I can do that!** There is a "Visual" tab in the "Edit dial" window so I will probably add it there.

4. logo change was also requested many times and I have some new logos prepared, I just need to add the code for hot-swap which is not trivial. But it's planned.

5. login info in the main menu is a good point! Many apps have the login info displayed in the main menu so I should probably add it there as well. I'm writing this to my todo list! Thanks for pointing this out!

6. there is currently no 2FA so I would suggest you to use strong, ideally generated password :).
However, I like security features and I love staying up-to date with modern technology so adding some authenticator sounds cool. I probably can't afford any SMS option but those generated codes in phone apps should be doable. I'll look into it now!
