### ISSUE TITLE
Search by dial name does not show any result for a multi-select dial (unless the first character is omitted)

### ISSUE THREAD

**Issue by vivdev** [fastaddons/GroupSpeedDial#151]
**How to reproduce:**
(_Screenshots are shown in this note:_ https://www.evernote.com/l/AHe1hu6z-OxGBqzGQFWP-Lz9NtvSNCuYDg0/)

1. I created two test dials - one text dial SomeText and one multi dial SomeMulti - which I named uniquely  so search will not collide with anything else in my dials.

2. Now Ctrl Shift F to open search.  If I search "Some" only SomeText is shown in results.  SomeMulti is missing.

3. If I search "Multi", SomeMulti is shown.

4. The problem is first character is not being searched for multi dials.  E.g. if I search "omeMulti" or any keyword without the first character "S", it will correctly show SomeMulti.

**Comment by fastaddons** [comment]
Thank you for reporting!
I can confirm the name of dial or name of the page in multi-dial is somehow ignored.
I'm fixing it now and it will be fixed in the next release 21.2, most probably by the end of this week.

**Comment by fastaddons** [comment]
Fixed, thanks a lot for reporting this! I can't believe I've made such a dumb mistake in my code... it was actually broken only if the dial name started with search term, so if would search for "ulti" instead of "Multi", it would find it.

I'll release new version any day now, I have a few more small bugs to fix and I'm also finishing brand new "List layout" for the upcoming release.
