### ISSUE TITLE
Folder support within each Group

### ISSUE THREAD

**Issue by Mav3r1x** [fastaddons/GroupSpeedDial#17]
Hi,

This is a feature request that I have been looking for many similar addons but haven't found. Would it be possible to combine bookmarks in a folder, within groups?

**Comment by fastaddons** [comment]
Hello,
You can already organize your dials into groups and create "group-dials" (dial that points to a group), just like folders on your drive.
There is also special option in the Options page / Groups / "Hide nested groups from group list (top bar)" which will show only root groups in the group list. So nested groups won't be there.

With a Pro version you can also split one dial into multiple smaller (1x2, 2x1, 2x2, 3x3, 4x4 dials)

There will be a proper "tree-like" support in the future.

**Comment by Mav3r1x** [comment]
Hi,

Just bought the pro version and I gotta say that splitting one dial into multiple smaller dials is an amazing feature.

I just wish there were more customization options regarding the dial appearance (like cards instead of glow).

**Comment by fastaddons** [comment]
Thanks for your support!

As always, I'm opened to suggestions. 
I'm no designer so don't expect perfect design from me :), that's why I need a feedback and suggestions.
But I'm planning to add new visual themes for dials soon. I will try to imitate some other popular "dial" designs, like the one in Windows menu.
