### ISSUE TITLE
Add Firefox settings pages like `about:config`

### ISSUE THREAD

**Issue by cipricus** [fastaddons/GroupSpeedDial#185]
For the moment Firefox settings pages like `about:config`, `about:memory`, `about:performance` can be added but do not work when clicked .

![image](https://user-images.githubusercontent.com/3447868/200322946-0d3311ba-9e10-4311-9bf0-4c92baa47dc0.png)

**Comment by fastaddons** [comment]
Sadly, this is currently blocked by Firefox due to security:
https://bugzilla.mozilla.org/show_bug.cgi?id=1269456

So all "about:\*" pages and also all "moz-extension://\*" pages (except addon own pages) are blocked.
You can only copy the dial URL with right click / "Copy link location" (or by pressing "a").
