### ISSUE TITLE
☻Imports of bookmarks.html to GroupSpeedDial is not supported.

### ISSUE THREAD

**Issue by procodeing7** [fastaddons/GroupSpeedDial#212]
Imports of bookmarks.html to GroupSpeedDial is not supported.

Every once in a while I need to fetch my data from a different computer that had bookmarks.html on Google Chrome.
After the start there is no way to add bookmarks.html
, and this is a major glitch in your software.

**Comment by fastaddons** [comment]
Interesting, I didn't know one can export Chrome bookmarks, I had google it to find out how!
I'll see what I can do. It should be possible, although it's not a standard HTML so it will be tricky...

**Comment by bingling00** [comment]
> 



> Interesting, I didn't know one can export Chrome bookmarks, I had google it to find out how! I'll see what I can do. It should be possible, although it's not a standard HTML so it will be tricky...

User can import favorites only when open it for the first time.You can add an option to open the import interface at any time.

**Comment by fastaddons** [comment]
That's also planned. The problem is that it would replace your existing dials data. That's why it's currently available only during the initial setup when user has no dials.
And it's missing from the Options page because it's build using a different framework which is not compatible with my very old Options page (which I plan to upgrade...).
