### ISSUE TITLE
Right click menu in dark mode

### ISSUE THREAD

**Issue by Mav3r1x** [fastaddons/GroupSpeedDial#22]
the right click menu and hamburger menu should be black/dark in dark mode.

![image](https://user-images.githubusercontent.com/29626468/93203451-c2754400-f754-11ea-9905-c03d71c4a981.png)

**Comment by fastaddons** [comment]
I know, right? :)
I will check it out. I'm a bit worried about those icons as they may not be that visible on a dark background.
Also I'm a bit worried if people will complain, so maybe I should include an Option to change it.

**Comment by Mav3r1x** [comment]
I agree. Having an option would be better. You could choose a different shade of black so it doesn't blend in with a dark background completely.

**Comment by Juraj-Masiar** [comment]
Don't worry, it won't be pitch black :), I will take some commonly used dark color, probably something like Windows uses in their dark context menu.
But I don't think I will do the color picker for this. Advanced users will be able to customize it through custom CSS styles set in the Options page.

Actually you can already use custom CSS to make it dark! Just copy and paste this to Options page / General / Custom CSS:
```
context-menu * {
    background: #575757 !important;
    border-color: gray !important;
}
context-menu {
    background: #575757 !important;
    color: white;
}
```
But it's not perfect because the mouse-hover effect will be lost.
I will have to refactor the code a bit... the menu was originally build for different environment...

**Comment by Mav3r1x** [comment]
Thanks for the CSS code. I am willing to sacrifice the hover effect xD

I do hope that you decide to move away from "glow" effect, or atleast give choice to have something like a card effect.

**Comment by fastaddons** [comment]
I have to say, I surprised myself how good it looks considering how little work I've put into it :D.
So I think I will try to prioritize this and make a proper dark style in the next release.

By the "glow" effect, you mean the shadow?
I agree, it's not always used right. It suppose to be used to add 3D effect (like when something is above something) but sometimes I use it just to highlight stuff...
I'm planning big visual upgrades in upcoming versions so stay tuned :)

**Comment by fastaddons** [comment]
New version 15.3 has been released now (for Firefox, Chorme version is being reviewed so hopefully in a day or so...) and it brings Dark mode switch for user interface (except for Options page, that one still needs to be rebuild to new material design).

Dark mode switch is in the Edit dial / Edit group window and it will make context menus dark as well.
