### ISSUE TITLE
Login icon disappeared in Safari

### ISSUE THREAD

**Issue by cencio1952** [fastaddons/GroupSpeedDial#223]
**Describe the bug**
The login icon has disappeared, as can be seen from the screenshot attached

**Steps To Reproduce**

**Expected behavior**

**Device info:**
 - operating system: MacOS Ventura
 - Browser and version: Safari 16.3
 - GroupSpeedDial version: 22.3

**Additional info**
Add any other info about the problem here.
<img width="185" alt="Screenshot 2023-02-11 at 11 07 07" src="https://user-images.githubusercontent.com/57355153/218252571-090ea3aa-e6ce-4977-9e49-e15ac845e595.png">

**Comment by fastaddons** [comment]
Yeah, I had to remove it as result of a terrible compromise :(

The problem is that Apple would not allow me release updates for my speed dial unless I add option to "Login with Apple" to my cloud server. Because if addon supports login with Google, it must also support login with Apple.

However adding new OAuth method is not an easy task. I've already regretted adding login with Facebook since not many users used it and Facebook made me go through several security checkups and even disabled it for some time.

So as a quick hotfix, I've removed all "login" buttons.
The synchronization still works though, it's just hidden from the interface. So as long you are logged in to your account, things should work as before.

Also, you can actually un-hide it with a simple trick:
1. open Options page
2. on the General tab, enter this into "Custom CSS styles" box:
```css
#login { display: flex }
```
3. click Save changes

**Comment by cencio1952** [comment]
Thanks!

**Comment by fastaddons** [comment]
Let's leave this issue open so that others can see it until I actually make a proper fix.

**Comment by Juraj-Masiar** [comment]
All my Safari extensions are now deprecated:
https://ko-fi.com/post/Im-done-developing-Safari-extensions-D1D3MYJPL
