### ISSUE TITLE
cloud speeddial shows up like a long list

### ISSUE THREAD

**Issue by bartveld** [fastaddons/GroupSpeedDial#289]
Since today https://group-speed-dial.fastaddons.com/cloud/ gives me a very long list (including graphics) of my dials, instead of the slick one-screen with all the dials. Of course, the local version of the dials gives no problems. Very strange.

 - operating system:  Windows 10
 - Browser and version: Firefox latest
 - GroupSpeedDial version: 23

Attached a screenshot of a part of it (page is waaaay to long for a single screenshot)
![Screenshot_1](https://github.com/fastaddons/GroupSpeedDial/assets/14937413/62118329-71bf-4118-8aec-540ca70ab069)

**Comment by Juraj-Masiar** [comment]
Hello,
I did released new cloud version today (and also yesterday). So there is a good chance I've broke something.
But first, could you try to reload the page:
- first simply reload, for example by pressing F5 key
- second, try to reload using "Ctrl + F5", or "Ctrl + Shift + R" (this will do a hard reload without using cache)

**Comment by bartveld** [comment]
Hi Juraj,
Thanks for the quick response. A simple F5 seems to have resolved the problem. Could have thought of that myself, I suppose.

**Comment by Juraj-Masiar** [comment]
Thank you for the info!
This is indeed some issue with the cache so this may break every time I release new cloud version (which is not often, but still, I'll better fix this asap).
Thanks again for reporting this!

**Comment by Juraj-Masiar** [comment]
I think I've fix it for the future releases.
What I suspect is happening is that browser may cache old "index.html" file that points to no longer existing CSS and JavaScript files (like "/cloud/dial.f34c2a276622004a35de.js"). So to fix this, I will no longer remove old files during the deploy so that cached clients can still access them.

Anyway, thanks again for reporting this! :)
