### ISSUE TITLE
Ctrl+number doesn't work properly after v25.0

### ISSUE THREAD

**Issue by morrogenduath** [fastaddons/GroupSpeedDial#324]
**Describe the bug**
I can only activate ctrl+2, ctrl+3 or ctrl+4 with the speed dial after updating to version 25.0

**Steps To Reproduce**
Choosing any other combination (ctrl+8, ctrl+12, etc.) doesn't activate the appropriate link from the speed dial.

**Device info:**
 - operating system: Manjaro
 - Browser and version: Firefox 123.0
- Ctr+number addon version: 2.7resigned1
- Group Speed Dial version: 25.0

**Comment by Juraj-Masiar** [comment]
Thanks for reporting, I'll investigate it now.

**Comment by bathindahelper** [comment]
For me too. When I press a shortcut it (FF) tries to (flashed for a micro second) the same tab number as the shortcut key I pressed. E.g. If I pressed Ctrl+4 then 4th tab in the FF Browser will flash for a tiny second but nothing will happen. And if I press higher number (e.g. Ctrl+9 or 0),then nothing visibly happens.
Full details with the screen shots can be seen [here](https://bathindahelper.com/t/ff-addon-group-speed-dial-ctrl-number-keys-stopped-working-on-my-firefox-browser/4405/2?u=bathinda_helper).

**Comment by Juraj-Masiar** [comment]
As a workaround, you can downgrade to the previous version:
https://addons.mozilla.org/addon/groupspeeddial/versions/
But make sure to export your dials to a file from Options page / Import backup tab / Export all. Just to be sure so that you have a full backup.
You will also need to disable auto-update for my addon in the "about:addons" page. Ideally only temporarily until I fix it.

I still don't have it fixed but I'll to fix it today. I had some urgent server issues I had to attend to yesterday.
Also, I woke up a bit sick today so my productivity is down :(
I'm sorry for the issues!

**Comment by morrogenduath** [comment]
Please take care of yourself first. A broken Juraj is no good to us :-D

**Comment by bathindahelper** [comment]
@morrogenduath  are you saying something to me pls? Have I said something wrong?

**Comment by Juraj-Masiar** [comment]
@bathindahelper I think all messages here are addressed to me :).

I've just finished fixing this issue, so it will work again in the next release.
Let me just fix one more issue and I'll submit it for review.

**Comment by Juraj-Masiar** [comment]
Good news! New version has just been approved!
I can't believe it took a whole leek... maybe due to public holiday in the middle of week.
Any way, if you haven't been updated yet, you can check for updates now from about:addons page:
https://github.com/fastaddons/GroupSpeedDial/wiki/How-to-update-to-latest-version#firefox
