### ISSUE TITLE
FEATURE REQUEST:  "Save without Updating Thumbnail" 

### ISSUE THREAD

**Issue by v9xz** [fastaddons/GroupSpeedDial#332]
GROUP SPEED DIAL version 25.2 : FEATURE REQUEST

The problem: The option for Thumbnails -> Auto-reload settings -> "Disable in this browser" does not work when changing urls inside a dial. In such cases, the thumbnail proceeds to auto-update anyway, overwriting the old thumbnail.

Is there an option I'm missing? Something to bypass the auto-update feature completely?
Please advise.

The problem continued: When the thumbnail auto-updates in such cases, it destroy the old and wastes the time spent creating it. And while there is no feature to generate jpgs from thumbnails, the only method to restore the old thumbnail is to reload an old export file, or to completely redo the steps made to create it. 

POSSIBLE SOLUTIONS:
Devise a method to allow url changes without auto-updating the thumbnail. Such as,
1) An option to "Save without Updating Thumbnail", OR
2) Modify the option to "Save" where it only applies the changes, adding a button to "Update Thumbnail" to the side, OR
3) Modify "Disable in this browser" to work even after url changes, OR
4) An option to "Revert to previous Thumbnail" and/or "Undo Thumbnail Update"

Thanks for your continued work on this addon!

note: with such modifications or changes as proposed above, the "Auto-generated thumbnail" designation would not be entirely accurate (as seen inside 'Edit Dial' -> 'Thumbnail').

**Comment by Juraj-Masiar** [comment]
Hello,
The option "Auto-reload settings -> "Disable in this browser" " applies only to dials that have "Auto-reload" feature enabled (when dial thumbnail auto-updates in a specific time interval).

The issue you have is the automatic thumbnail update when URL changes. Which is in most cases desirable, since new URL means the thumbnail is most likely not matching the page anymore.

However, the thumbnail should only change if the domain changes, so it's actually a bit broken right now, I see I've broke it in March this year. I will fix that so that change in URL will not reload thumbnail, as long as the domain name stays the same, so change from "example.com/1" to "example.com/2" will not trigger reload, only if you change it to "example.org" or "x.example.com".

Note that in the meantime, you can revert previous thumbnail for any dial from context menu / Advanced / Restore previous thumbnail.

**Comment by Juraj-Masiar** [comment]
Done, it will be fixed in the upcoming 25.4 version. 
Probably around next week, I still have a quite a few features to implement...

**Comment by v9xz** [comment]
Thanks for getting back to me.

"context menu / Advanced / Restore previous thumbnail" is an acceptable workaround, and I was unaware of its existance.
