### ISSUE TITLE
Show full speed dial frames and not only upper half?

### ISSUE THREAD

**Issue by tobwz** [fastaddons/GroupSpeedDial#45]
Currently each speed dial frames show only the upper half of the underlying webpage. See attached snapshot

Is this correct?

if not: How can I tell Group Speed dial to show/fill the whole fame?

![half speed dial frames](https://user-images.githubusercontent.com/60912225/117342104-1fb83400-aea3-11eb-89cc-98875b2814d5.png)

**Comment by fastaddons** [comment]
Hello,
Oh man, I was hoping I've fixed this already :(
Do you have by any chance a super wide screen? Something like 32:9 or even 21:9?
Anyway, go the Options page / Thumbnails / "Auto-reload target screen resolution" and change it to "Manual".
Then set the first value to half of what you see and keep the second value same as it is.
That should fix the problem - but you need to reload your thumbnails.

The problem is that the thumbnail dimensions are calculated based on user screen - so that it looks good when using full-screen mode (or maximized window). But users with wide screens are never using that.

**Comment by tobwz** [comment]
So ok my monitor has a resolution of 3440x1440pixels

When I open the WebExt Options the two entry fields show
3440 x 1316

I changed it to Manual and
1720 x 1316
save it and opened a new tab but no change: Only half of the thumbnail is changed
Finally I tried the two values pairs

3440 x 1440
or
1720 x 1440

No change.
Any other suggestion?

**Comment by fastaddons** [comment]
Did you reload the thumbnail? You need to re-generate them, try it on one of them, right click / Refresh image. If it works, you can reload all at once from the main menu.

**Comment by tobwz** [comment]
Ah ok. 

I works :-)
