### ISSUE TITLE
Switch to new tab, not working in latest GSD update in Firefox

### ISSUE THREAD

**Issue by JimDop** [fastaddons/GroupSpeedDial#60]
This just seemed to break in the latest version of GSD . Was working until I updated it today. 

  When opening in a new tab, it does not switch to the new tab, even though that option is activated.

**Comment by fastaddons** [comment]
Hello,
Thank you for reporting!
The fix is ready, I will release it in a few hours in 16.1 version

**Comment by HajoScheepmaker** [comment]
I'm not sure if this was known and/or solved, but the same issue occurres in the Chrome-version.
Thanks for your great work though!

**Comment by fastaddons** [comment]
Yeah, It's bug in the 16.0 release on both platforms. 
I made a fix yesterday evening but it's still buggy. I'm working on right now and I will release it as soon as it's ready.
But I will need few more hours because the original code is many years old so I'm rewriting it to a better architecture to prevent issues like this in the future.
Please be patient, I will do my best to fix it ASAP.

**Comment by Alenet-business** [comment]
Same in Edge (Chrome based).

**Comment by Alenett** [comment]
Same in Edge (Chrome based).

**Comment by fastaddons** [comment]
Done!
Firefox version 16.1 has been released, go to "about:addons" and click "Check for updates" in the gear icon menu to update now.

Chrome version is being reviewed by Chrome Store which usually it takes about 12 hours to get approved. Sometimes much less, sometimes much more.

Hopefully I didn't break other things because I rewrote a huge part of the legacy click handling...

**Comment by JimDop** [comment]
Thanks for the fast fix on this.   Just tested on Firefox and looks good!
