### ISSUE TITLE
No Thumbnail Option

### ISSUE THREAD

**Issue by TESTESTJP** [fastaddons/GroupSpeedDial#63]
Hello! I really enjoy this addon but I have a problem.
My Brave browser always crashes with this addon.
I think it happens simply because I get 300+ dials.  
So I guess main problem is thumbnail. Loading thumbnails of 300+ dials must be heavy.
That's why I wish I had "No thumbnail for all(this tab's) dials" option or something.

Sorry for my English. Regards.

**Comment by fastaddons** [comment]
Hello,
Let's investigate if it is really related. Could you post the "Data size" from your statistics here?
You can find it here:
![Screenshot 2021-08-05 18 42 18](https://user-images.githubusercontent.com/55486931/128389079-96e1d50a-d731-499b-a643-5221bc68b18d.png)

Also, check the Brave "Task manager". You can open it from the main menu or with "Shift + Esc" shortcut.
Look there how much memory is my speed dial taking (it's the first column, Memory footprint).

There are ways to make thumbnails smaller - in the Options page / Thumbnails / "Use high resolution" (at the bottom of the page).
You can uncheck it and then reload all thumbnails. All new created will use normal resolution so that should make them 1/3 of their size or even smaller without reducing quality much.

Also, you should not have 300 dials in a single group. Organizing them into groups would make it easier to find what you are looking for and it would load them faster as well.
But even with 300 dials in a single group it should be still fast enough. Check the Brave taks manager to see if other extensions are not taking too much memory.

**Comment by TESTESTJP** [comment]
Data size is like...
![01](https://user-images.githubusercontent.com/88499830/128391640-2e624361-52a2-4270-bf74-5b4552101a6c.png)

Task manager is here. Yeah, Group Speed Dial doesn't eat so much memory indeed. You're right,
![02](https://user-images.githubusercontent.com/88499830/128391650-65250f3d-2297-4f3f-8d86-7f2c1d40ba23.png)

＞"Use high resolution" 
Yeah. I'm using this but still feel heavy. 
At least without Group Speed Dial, my Brave browser seems well.

**Comment by fastaddons** [comment]
These values looks ok,
**Try to disable the "Use high resolution" option and then reload all thumbnails.** 
That should make it much less heavy to load. Try it.

**Comment by TESTESTJP** [comment]
I meant already turned off "Use high resolution" option. But I now realize that I also turned off auto reload thumbnails.
It stands I thought using lower resolution thumbnails but kept using higher resolution thumbnails, right? so sad :/
At least I feel slightly faster right now but I need keep using for checking how it actually works.
Thanks so much today. I have to go bed...
