### ISSUE TITLE
Can't access top dials because covered by list of groups

### ISSUE THREAD

**Issue by KitKestrel** [fastaddons/GroupSpeedDial#66]
**Describe the bug**
I have over 1200 dials organized into several dozen groups.  Because I'm a pro member, the index of groups forms a horizontal bar at the top of the window.  When I want to reorganize dials on a group, I pick one up and the whole set of groups drops down, which is fine if I want to move the dial to another group, but if I want to move the dial to the top rows of the same group, I can't because they are covered by the list of groups.

**Steps To Reproduce**
Create a group with many dials so that when it's viewed, each dial is only a couple of centimeters high.  Add a site to a dial near the bottom.  Then create enough groups to create several rows in the group index when it is displayed horizontally.  If you create enough groups with long enough names, you'll cover the top row/rows of the active group.  Pick up the dial you created before.  The group list automatically displays, covering the top rows of dials in the active row.

**Expected behavior**
Top rows of the active dial should be accessible. 

**Device info:**
 - operating system: PC laptop, Windows 10
 - Browser and version: Firefox 90.0.2
 - GroupSpeedDial version: 16.2

**Additional info**
Add any other info about the problem here.
Love the program :-)

**Comment by fastaddons** [comment]
Hello,
Yes, this is a known problem. I also have a lot of groups and I noticed this a while ago. I have it on my todo list but nobody complained yet so I've let it be :)

So the main question now is, how to fix it?
I think I should disable the groups rollout and activate it only if you actually drag over the list - then show it. That way you can use drag and drop within same group without being disturbed.
I will also have to roll it back when you leave the area so that you are able to drop the dial somewhere near top after opening the target group.
I will try to implement this in the next version 16.3, sometime this week (depending how my other bugfixing will go).

Thank you for reporting bugs :)

**Comment by KitKestrel** [comment]
Thank you for your answer, and I think your fix sounds good. Thanks for the program!
Kit.

Typos courtesy of Google

________________________________

**Comment by fastaddons** [comment]
Fixed in 16.3, released just now.
Have a nice weekend :)

**Comment by KitKestrel** [comment]
Thanks!

Typos courtesy of Google

________________________________
