### ISSUE TITLE
New Browser Started when adding a site.

### ISSUE THREAD

**Issue by Jack-Zeh** [fastaddons/GroupSpeedDial#71]
Microsoft Edge. Clicking on Icon where Extensions are: Then I click on the  add this page to a dial. At that point a new browser is brought up - can add without a problem, just have to close this extra browser manually.
Am I missing an option that would fix this? Tried the ones with new tabs and other options - didn't work.

Thanks for your help.
Jack
![image](https://user-images.githubusercontent.com/34869240/132518706-b9686fcb-c06b-46bf-913e-c4774ddeaa46.png)

![image](https://user-images.githubusercontent.com/34869240/132518799-78f42a22-03ea-4b52-a9e8-b86ef7345451.png)

![image](https://user-images.githubusercontent.com/34869240/132519383-828210d4-669d-488d-aebf-185f83b69559.png)

**Comment by fastaddons** [comment]
Hello,
Yeah, the new behavior with the new window being opened is to hide the screenshots making in the original tab (when using "Add X tabs to dials").
I guess I could open a new tab instead when using is adding only one page, but I'm not sure if it can be done easily since the code is asynchronous and now I would have to take the screenshot before opening new tab...
But anyway, there are two easy solutions:
- after you click on the dial where you want to add the page, you should see a modal window with a big button at the bottom "Return to tab" that will close the window and return you back to the tab
- if you always want to return back to the tab, you can enable it in the Options page / General / "After adding current page to dials: Return to previous tab"

**Comment by Jack-Zeh** [comment]
Thanks. That works nicely.

Jack
