### ISSUE TITLE
error 413 try again later

### ISSUE THREAD

**Issue by JohnJohn45** [fastaddons/GroupSpeedDial#78]
Hi,

**Describe the bug**
"error 413 try again later" when I try to synchronize dials

**Steps To Reproduce**
Click on sync button

**Expected behavior**
my dials will be synchronized with my account

**Device info:**
 - operating system: Windows 11
 - Browser and version: firefox 93 (x64)
 - GroupSpeedDial version: 16.6

**Additional info**
[log.txt](https://github.com/fastaddons/GroupSpeedDial/files/7357322/log.txt)

sorry for my english

**Comment by fastaddons** [comment]
Hello,
Could you paste here the "Data size" section of the Statistics? You can open it from the main menu on the dials page / Advanced / Statistics.
I think it's too big request, but let's verify with the statistics data.

**Comment by JohnJohn45** [comment]
thank you for your quick answer

Dials info 
Groups: 3
Dials (not empty): 126
URL dials: 126
Group dials: 0
Search dials: 0
Live dials: 0
Multi dials: 0
Multi dial links: 0
Text dials: 0
Auto reload dials: 0
Data size 
IndexedDB (img + back): 9.1MB
storage.s: 25.8KB
storage.l: 2.9MB
localStorage: 218.0B
Dials: 2.8MB
Options: 2.2KB

**Comment by fastaddons** [comment]
Interesting!
So you use the "Custom thumbnail from URL:" option, right?

My addon was using dataURL strings to store images before but I had to refactor it into Blobs because some other addons were scanning these long strings and it was causing a huge performance issues.

Anyway, to replace image you can maybe hold "Shift key" and right-click on a dial image and select "Use this image as thumbnail" and then click on the same dial. That should store it as file in the database.

**Comment by JohnJohn45** [comment]
After replace all my thumbnails with PNG files, all is good ! thank you for your help !
