### ISSUE TITLE
How to prevent background refreshing feature steals my focus of window?

### ISSUE THREAD

**Issue by Honsal** [fastaddons/GroupSpeedDial#94]
Whether *background* or *background 2*, refreshing thumbnails will make my window focus lost.

I was writing code using Visual Studio on main monitor. Then suddenly my main monitor was ***flashed/blinked*** once, and my typings(3-4 characters) are gone.

I found it is caused by background refreshing of thumbnail. No matter auto-reload or manual, on both mode(background/background 2) will cause this situation.

It works perfectly fine on Firefox. But chromium-based browsers is not. I have tested on Chrome and Edge.

Sorry for my bad english. Below is translated content.

```
[Auto-translated content]

Regardless of whether it is background or background 2, there is a bug that loses the focus of the application when reloading thumbnails in the background.

The reason for losing thumbnails is that when reloading in the background, a chrome window appears and disappears on the main monitor for a very short time (less than 200 ms), and the existing application seems to lose focus as the chrome window takes focus.

For example, when coding in Visual Studio(main monitor) with running chrome(sub monitor), a few dials start automatic reloading, which causes the above symptoms within a few seconds and prevents 3-4 letters of code from being typed.

These symptoms appear to occur only in chromeium-based browsers (tested with Edge, Chrome), and work perfectly without problems in Firefox.

I wonder if it is a limitation of the chromium extension API or a problem that can be modified.
```

---

Hardware information
- Monitors: QHD(Main), FHD(Sub)
- Browser: Chrome
- OS: Windows 10 19043.1387

**Comment by Honsal** [comment]
closed due to no comment

**Comment by fastaddons** [comment]
Hello,
I'm sorry for the delay, I was finishing the 17.1 release which I wanted to release several days ago so I was focusing on it.
The background reload doesn't work well in Chromium browsers, only Firefox has "hidden tabs" feature which works very well.
I've tried to make it without focus, but it doesn't work.
I have to say, the thumbnails generation is one of the worst things I've ever programmed. It's fragile, it breaks often with new browser versions and it's browser specific. I will be adding "remote reload" in the future which will be creating thumbnails in the cloud, but I'm not sure when exactly...

**Comment by Honsal** [comment]
@fastaddons Thanks for reply. I think it could be local server too. Download executable, register to service or startup program without UI(or hide), and communicate with GroupSpeedDial with websocket or so.
I don't know details of your plan, but it could be too expensive. Selenium/Puppeteer screenshot feature is using too much resources on every request.
But, local server can handle it. Start Selenium/Puppeteer with headless mode will not steal focus, and server-cost-problem will be solved.

It is just a suggestion. Thanks for read.

**Comment by fastaddons** [comment]
Interesting idea!
I'm actually planning to create a companion app but for a different purpose. So using it also for thumbnails generation is interesting for sure. 
But this is not that easy. I would have to bundle a whole browser which I would have to update all the time to keep it secure.... or somehow use OS web-view component, if that's still a thing. And even then, screenshots without adblock may look bad. And many people simply won't install 3rd party software for addon because of various reasons.

My "cloud reload" plan is actually to use some of the Raspberry Pi devices I already have. Since loading a web-page may be a dangerous thing (in case of 0-day vulnerabilities), I don't plan to use my main server for that - it will only send work to these small worker devices.
But even this approach is not perfect since many pages are locked for a specific region (like streaming services that exists only in specific countries).

So as you can see, there is no easy solution. The best would be if Chrome could implement the Hidden Tabs API like Firefox.
